version: '3.8'

services:
  db:
    image: postgres:16
    container_name: petfamily_postgres
    environment:
      POSTGRES_DB: PetFamily
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U PetFamily"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ${DOCKER_REGISTRY-}petfamilyapi
    build:
        context: .
        dockerfile: src/PetFamily.API/Dockerfile
    ports:
    - "8080:80"
    depends_on:
     db:
      condition: service_healthy
     seq:
      condition: service_started
     minio:
        condition: service_started
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=PetFamily;Username=postgresUser;Password=postgresPassword
    - Serilog__WriteTo__0__Name=Seq
    - Serilog__WriteTo__0__Args__serverUrl=http://seq:5341
    restart: unless-stopped 

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped 
    environment: 
    - ACCEPT_EULA=Y
    - SEQ_FIRSTRUN_ADMINPASSWORD=admin1234
    ports:
    - 5341:5341
    - 8081:80  
    volumes:
    - seq_data:/data
   
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
    - minio_data:/data
    command: server /data --console-address ":9001"
   



  

volumes:
  postgres_data:
  seq_data:  
  minio_data:  